### ISSUE TITLE
Connexion is not commonly used in British English

### ISSUE THREAD

**Issue by TE-vinhdinh** [hyperreality/American-British-English-Translator#17]
While connexion is a valid alternative spelling of connection, is is not used commonly in British English anymore

**Comment by AntonOfTheWoods** [comment]
Why on earth would you remove this? Just because something is now rarely used, doesn't mean it isn't used. For example, the Oxford scholar and inaugural chair of their linguistics department Roy Harris used it exclusively in his many books and articles until his passing in 2015.

Why remove it? Because it is also a French spelling? We have lots of those...
